name: Windows Build

on:
  workflow_dispatch:

jobs:
  build-windows-cli:
    name: Build for Windows x86_64
    runs-on: windows-latest

    steps:

      - uses: actions/checkout@v4

      - uses: lukka/get-cmake@latest

      - run: |
          mkdir build
          cd build
          cmake ..
          make

      - run: ls
      - run: dir

      - uses: actions/upload-artifact@v4
        with:
          name: Simulator
          path: ./Simulator.exe